SELECT * FROM ecommerce.order_items;

## 1. Calculate the total revenue generated by each seller and rank them in descending order based on their earnings
with total_revenue as (select order_items.seller_id, sum(payments.payment_value) total_revenue from order_items join payments on order_items.order_id = payments.order_id group by seller_id)
select *, dense_rank() over (order by total_revenue desc) from total_revenue;